function combine_all_SEGGA_outputs_in_one_file(save_dir)

if (nargin <1) || (~isdir(save_dir)) || isempty(save_dir)
    save_dir = [pwd,filesep,'..',filesep,'text_output',filesep];
end

output_fname = 'analysis_data_SEGGA_output.mat';
%%% The following variable names are used to access that variable from 
%%% the function , 'set_var_for_plot_SEGGA'.
varname_list = {...
                'num_cells_sel',...
                'nghbrs_lost_per_cell',...
                't1_per_cell',...
                'ros_per_cell',...
                'nghbrs_gained_per_cell',...
                'hor_elon',...
                'ver_elon',...
                'longaxis_elon',...
                'shortaxis_elon',...
                'hor_to_ver_ratio',...
                'L1_to_L2_ratio',...
                'norm_hor_to_ver_ratio',...
                'norm_L1_to_L2_ratio',...
                'top_dis',...
                'num_nghbrs',...
                'node_multiplicity',...
                'edge_align',...
                'cell_hor_length',...
                'cell_ver_length',...
                'norm_cell_hor_length',...
                'norm_cell_ver_length',...
                'cell_hortovert_length',...
                'cell_vertohor_length',...
                'norm_cell_hortovert_length',...
                'cell_area',...
                'norm_cell_area',...
                'cell_area_coefficient_of_variation',...
                'cell_ecc',...
                'cell_ang',...
                'pat_defo',...                
                'num_shrink_selected',...
                'all_contract_rate_mean',...
                ...'vert_contract_rate_mean',...
                'ros_contract_rate_mean',...
                't1_contract_rate_mean',...
                ...'len_sh_mean',...
                ...'len_gr_mean',...
                'cells_lost_hist',...
                'cells_gain_hist',...
                'cells_t1_hist',...
                'cells_ros_hist',...
                'num_sides_hist',...
                ...'t1_to_ros_ratio',...
                'perc_nlost_ros',...
                'perc_nlost_t1',...
                'cells_at_least_one_event_anykind',...
                'cells_at_least_one_T1',...
                'cells_at_least_one_rosette',...
                'cells_at_least_two_rosettes',...
                'cells_w_edges_shrink_into_at_least_one_event_anykind',...
                'cells_w_edges_shrink_into_at_least_one_T1',...
                'cells_w_edges_shrink_into_at_least_one_rosette',...
                'cells_w_edges_shrink_into_at_least_two_rosettes'...
                };
            

load shift_info
vars = [];
mapped_names = [];
for j = 1:length(varname_list)
    vars = set_var_for_plot_SEGGA(vars,varname_list{j});
    mapped_names(j).name = movie_var_name_mapping_SEGGA(varname_list{j});
end

meas_dir = [save_dir,filesep,'measurements',filesep];
if ~isdir(meas_dir)
    mkdir(meas_dir);
end

for i=1:length(vars)
    if isempty(dir([vars(i).file_name,'*']))
        display(['missing analysis data file: ',vars(i).file_name]);
        display('try rerunning analysis if analysis is stale');
        continue
    end
	d = load(vars(i).file_name, vars(i).var_name);
    if ~isfield(d,vars(i).var_name)
        display(['could not find variable: ',vars(i).var_name]);
        display('try rerunning analysis if analysis is stale');
        continue
    end
    if isfield(vars(i), 'func') && ~isempty(vars(i).func)
        d.(vars(i).var_name) = vars(i).func(d.(vars(i).var_name), shift_info);
    end
    eval([varname_list{i},' = d.(vars(i).var_name);']);
%     tmp = flatten(d.(vars(i).var_name));
%     display(size(tmp));
    if isempty(dir([save_dir,filesep,output_fname]))
        save([save_dir,filesep,output_fname],varname_list{i});
    else
        save([save_dir,filesep,output_fname],varname_list{i},'-append');
    end
    tmpvar = d.(vars(i).var_name);
    display(['var_name: ',vars(i).var_name]);
    if any(size(tmpvar)==1)
        tmpvar = reshape(tmpvar,max(size(tmpvar)),1);
        eval([varname_list{i},'=tmpvar;']);
    end
    eval(['csvwrite([meas_dir, ''', mapped_names(i).name,''',''.csv''],',varname_list{i},');']);
end

load('analysis','seq');
cells_map = seq.cells_map;
save([save_dir,filesep,output_fname],'cells_map','-append');
inv_cells_map = seq.inv_cells_map;
save([save_dir,filesep,output_fname],'inv_cells_map','-append');
edges_map = seq.edges_map;
save([save_dir,filesep,output_fname],'edges_map','-append');
inv_edges_map = seq.inv_edges_map;
save([save_dir,filesep,output_fname],'inv_edges_map','-append');

[name_title_map(1:length(vars)).varname] = deal(varname_list{:});
[name_title_map(1:length(vars)).titlename] = deal(vars(:).title);
% display(name_title_map);
save([save_dir,filesep,output_fname],'name_title_map','-append');