function [all_possible_variables,all_possible_display_names] = give_possible_variables_to_SEGGA_extras()


all_possible_variables = {...       
        'perc_nlost_ros',...
        'perc_nlost_t1',...
        'cells_at_least_one_event_anykind',...
        'cells_at_least_one_T1',...
        'cells_at_least_one_rosette',...
        'cells_at_least_two_rosettes',...
        'cells_w_edges_shrink_into_at_least_one_event_anykind',...
        'cells_w_edges_shrink_into_at_least_one_T1',...
        'cells_w_edges_shrink_into_at_least_one_rosette',...%(active)
        'cells_w_edges_shrink_into_at_least_two_rosettes',...%(active)        
        };


all_possible_display_names = {...
        'Percent of rearrangements that are T1 transitions',...
        'Percent of rearrangements that are rosettes',...
        'Percent of cells in T1s or rosettes',...
        'Percent of cells in T1 transitions',...
        'Percent of cells in rosettes',...
        'Percent of cells in two or more rosettes',...
        'Percent of cells in T1s or rosettes (contracting only)',...
        'Percent of cells in T1 transitions (contracting only)',...
        'Percent of cells in rosettes (contracting only)',...
        'Percent of cells in two or more rosettes (contracting only)',...
        };


    

