function [all_possible_variables,all_possible_display_names] = give_possible_variables_to_SEGGA_shrink()


all_possible_variables = {...
        'num_shrink_selected',...
        'all_contract_rate_mean',...
        ...'vert_contract_rate_mean',...
        'ros_contract_rate_mean',...
        't1_contract_rate_mean',...
        };
    
all_possible_display_names = {...
        'Number of shrinking edges',...
        'Contraction rate of all shrinking edges',... 
        ...'Contraction rate of vertical shrinking edges',...
        'Contraction rate of shrinking edges that form rosettes',...
        'Contraction rate of shrinking edges that form T1 processes'...
        };


  
