function [all_possible_variables,all_possible_display_names] = give_possible_variables_to_SEGGA_barchartvars()



all_possible_variables = {...
        'cells_lost_hist',...
        'cells_gain_hist',...
        'cells_t1_hist',...
        'cells_ros_hist',...
        'num_sides_hist'...
        };
    
all_possible_display_names = {...
        'Histogram of neighbors lost',...
        'Histogram of neighbors gained',...
        'Histogram of T1 transitions',...
        'Histogram of rosettes',...
        'Histogram of number of cell sides'...
        };

