function [all_possible_variables,all_possible_display_names] = give_possible_variables_to_SEGGA_rotation()


all_possible_variables = {...
        'rot_edges_chan_one',...
        'rot_edges_chan_two'....
        };


all_possible_display_names = {...
        'Rotating Edges(DV->AP) Channel 1',...
        'Rotating Edges(DV->AP) Channel 2',...
        };


    

