function make_charts_from_settings(settings)
%%% Changed all instances of 'dirnames' to 'fullpath_dirnames' 2017-Jan-13
%%% (DLF), could create issues - need to test.
%%%
% note that 'savedir' was changed to 'save_base_dir'
% run the charts
settings.save_base_dir = [settings.save_base_dir,filesep,'time-series',filesep];

%%% using fullpath_dirnames for everything now
settings.movie_base_dir = filesep; %start from root

if iscell(settings.plot_style)
    settings.plot_style = settings.plot_style{:};
end

if iscell(settings.errorbar_style)
    settings.errorbar_style = settings.errorbar_style{:};
end

if isempty(settings.errorbar_style)
    display('errorbar_style is empty');
    return
end

display(settings.errorbar_style);

if strcmp(settings.plot_style,'single_movies_group')||strcmp(settings.plot_style,'single_movies_var')
    settings.dirnames = {settings.dirnames{[settings.groups(:).dirs]}};
end
% display(settings.groups(:).dirs);
% display(settings.dirnames{settings.groups(:).dirs});
% return
if isfield(settings,'vars') && ~isempty(settings.vars)
    switch settings.vars_type_ind
        case 1 %basic time series
            switch settings.errorbar_style
                case 'line'
                    h_all_out = plot_analysis_graphs(...
                        settings.plot_style,...
                        settings.vars,...
                        settings.fullpath_dirnames,...
                        settings.groups, ...
                        settings.movie_base_dir,...
                        settings.save_base_dir,...
                        settings.target_time_step,...
                        settings.time_window,...
                        settings.figsH,...
                        settings.text_string,...
                        settings.shift_hack,...
                        settings.unifydecimals,...
                        settings.xtra_txt,...
                        settings.ylim_input,...
                        settings.output_filetypes);
                case 'transparent'
                    solid_errs_bool = false;
                            h_all_out = plot_analysis_graphs_soliderrbars(...
                        settings.plot_style,...
                        settings.vars,...
                        settings.fullpath_dirnames,...
                        settings.groups, ...
                        settings.movie_base_dir,...
                        settings.save_base_dir,...
                        settings.target_time_step,...
                        settings.time_window,...
                        settings.figsH,...
                        settings.text_string,...
                        settings.shift_hack,...
                        settings.unifydecimals,...
                        settings.xtra_txt,...
                        settings.ylim_input,...
                        solid_errs_bool,...
                        settings.output_filetypes);
                otherwise
                    solid_errs_bool = true;
                    h_all_out = plot_analysis_graphs_soliderrbars(...
                        settings.plot_style,...
                        settings.vars,...
                        settings.fullpath_dirnames,...
                        settings.groups, ...
                        settings.movie_base_dir,...
                        settings.save_base_dir,...
                        settings.target_time_step,...
                        settings.time_window,...
                        settings.figsH,...
                        settings.text_string,...
                        settings.shift_hack,...
                        settings.unifydecimals,...
                        settings.xtra_txt,...
                        settings.ylim_input,...
                        solid_errs_bool,...
                        settings.output_filetypes);
            end
        case 2 % bar charts
            	h_all_out = plot_analysis_graphs_binned(...
                settings.plot_style,...
                settings.vars,...
                settings.fullpath_dirnames,...
                settings.groups, ...
                settings.movie_base_dir,...
                settings.save_base_dir,...
                settings.time_window(end),...
                settings.target_time_step,...
                settings.time_window,...
                settings.figsH,...
                settings.shift_hack,...
                settings.output_filetypes);
        case 3 % polarity
            combine_many_polarities_SEGGA(settings);
        case 4 % rotation
%             plot_analysis_graphs_soliderrbars_timegiven(action, vars, dir_names, groups, ...
%             home_dir, save_dir, target_time_step, time_lim, figsH, text_argin,shift_hack,...
%             unifydecimals,xtra_txt,ylim_input)
            plot_analysis_graphs_soliderrbars_timegiven(...
                settings.plot_style,...
                settings.vars,...
                settings.fullpath_dirnames,...
                settings.groups, ...
                settings.movie_base_dir,...
                settings.save_base_dir,...
                settings.target_time_step,...
                settings.time_window,...
                settings.figsH,...
                settings.text_string,...
                settings.shift_hack,...
                [],... %unifydecimals
                [],... %extra_txt
                settings.ylim_input);
        otherwise %this should not be reached
            if ~isstr(settings.vars_type_ind)
                var_type_str = num2str(settings.vars_type_ind);
            else
                var_type_str = settings.vars_type_ind;
            end
            display(['unknown type of variable: ',var_type_str]);
    end
end